import json
import os

def create_quiz(category, title, questions_data):
    return {
        "id": f"{category.lower()}-quiz-v3",
        "title": title,
        "category": category,
        "description": f"100 unique questions about {category}.",
        "questions": [
            {"text": q[0], "options": q[1], "correctOptionIndex": q[2]}
            for q in questions_data
        ]
    }

# --- SCIENCE (100 UNIQUE) ---
science_data = [
    ("What is the powerhouse of the cell?", ["Mitochondria", "Nucleus", "Ribosome", "Cell Wall"], 0),
    ("Which planet is known as the Red Planet?", ["Venus", "Mars", "Jupiter", "Saturn"], 1),
    ("What is the chemical symbol for water?", ["WA", "H2O", "HO2", "OH"], 1),
    ("What gas do plants absorb during photosynthesis?", ["Oxygen", "Nitrogen", "Carbon Dioxide", "Helium"], 2),
    ("How many planets are in our solar system?", ["7", "8", "9", "10"], 1),
    ("What is the hardest natural substance on Earth?", ["Gold", "Iron", "Diamond", "Quartz"], 2),
    ("Which force pulls objects toward Earth?", ["Friction", "Magnetism", "Gravity", "Inertia"], 2),
    ("What is the closest star to Earth?", ["Sirius", "Proxima Centauri", "The Sun", "Betelgeuse"], 2),
    ("What is the boiling point of water in Celsius?", ["90", "100", "110", "120"], 1),
    ("Which planet is famous for its rings?", ["Mars", "Jupiter", "Saturn", "Uranus"], 2),
    ("What is the center of an atom called?", ["Proton", "Neutron", "Nucleus", "Electron"], 2),
    ("Which gas makes up most of Earth's atmosphere?", ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"], 2),
    ("What is the largest mammal on Earth?", ["Elephant", "Blue Whale", "Giraffe", "Orca"], 1),
    ("What do bees collect from flowers to make honey?", ["Pollen", "Leaves", "Nectar", "Water"], 2),
    ("Which planet is the largest in our solar system?", ["Saturn", "Neptune", "Jupiter", "Uranus"], 2),
    ("What is the primary source of energy for Earth?", ["The Moon", "The Sun", "Coal", "Wind"], 1),
    ("Which part of the plant conducts photosynthesis?", ["Roots", "Stem", "Flowers", "Leaves"], 3),
    ("What is the chemical symbol for Gold?", ["Go", "Gd", "Au", "Ag"], 2),
    ("How many bones are in an adult human body?", ["206", "106", "306", "406"], 0),
    ("Which organ pumps blood through the body?", ["Lungs", "Brain", "Stomach", "Heart"], 3),
    ("What is the frozen form of water called?", ["Steam", "Vapor", "Ice", "Liquid"], 2),
    ("Which animal is known as the King of the Jungle?", ["Tiger", "Lion", "Elephant", "Leopard"], 1),
    ("Which part of the atom has a negative charge?", ["Proton", "Neutron", "Electron", "Nucleus"], 2),
    ("What is the name of the galaxy we live in?", ["Andromeda", "Milky Way", "Sombrero", "Cartwheel"], 1),
    ("Which vitamin is produced when skin is exposed to sunlight?", ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], 3),
    ("What is the smallest planet in our solar system?", ["Mars", "Venus", "Mercury", "Pluto"], 2),
    ("Which instrument is used to measure temperature?", ["Barometer", "Thermometer", "Hygrometer", "Speedometer"], 1),
    ("What is the chemical symbol for Iron?", ["Ir", "Fe", "In", "Io"], 1),
    ("Which organ is responsible for breathing?", ["Heart", "Liver", "Lungs", "Kidneys"], 2),
    ("What type of animal is a frog?", ["Mammal", "Reptile", "Amphibian", "Bird"], 2),
    ("Which is the fastest land animal?", ["Lion", "Cheetah", "Horse", "Greyhound"], 1),
    ("What is the first element on the periodic table?", ["Oxygen", "Helium", "Hydrogen", "Carbon"], 2),
    ("How many states of matter are commonly recognized?", ["2", "3", "4", "5"], 1),
    ("What is the name of the red pigment in blood?", ["Chlorophyll", "Hemoglobin", "Melanin", "Plasma"], 1),
    ("Which planet is known as the Evening Star?", ["Mars", "Jupiter", "Venus", "Mercury"], 2),
    ("What is the largest desert on Earth?", ["Sahara", "Gobi", "Antarctica", "Kalahari"], 2),
    ("Which part of the cell contains genetic material?", ["Cytoplasm", "Nucleus", "Membrane", "Wall"], 1),
    ("What is the speed of light?", ["300,000 km/s", "150,000 km/s", "500,000 km/s", "1,000,000 km/s"], 0),
    ("Which metal is liquid at room temperature?", ["Silver", "Mercury", "Copper", "Iron"], 1),
    ("Which gas is needed for a fire to burn?", ["Carbon Dioxide", "Nitrogen", "Hydrogen", "Oxygen"], 3),
    ("What is the name of the force that resists motion?", ["Gravity", "Friction", "Inertia", "Velocity"], 1),
    ("How many colors are in a rainbow?", ["5", "6", "7", "8"], 2),
    ("Which planet is the hottest?", ["Mercury", "Venus", "Mars", "Jupiter"], 1),
    ("What is the study of fossils called?", ["Biology", "Geology", "Paleontology", "Zoology"], 2),
    ("Which organ removes toxins from the blood?", ["Lungs", "Liver", "Stomach", "Heart"], 1),
    ("What is the most abundant element in the universe?", ["Oxygen", "Carbon", "Hydrogen", "Helium"], 2),
    ("Which planet is known as the 'Blue Planet'?", ["Mars", "Venus", "Neptune", "Earth"], 3),
    ("What do you call a rock that fell from space?", ["Asteroid", "Meteorite", "Comet", "Star"], 1),
    ("Which gas do we exhale most?", ["Carbon Dioxide", "Nitrogen", "Oxygen", "Hydrogen"], 1),
    ("What is the main component of the Sun?", ["Iron", "Oxygen", "Hydrogen", "Carbon"], 2),
    ("What is the scientific name for the voice box?", ["Trachea", "Larynx", "Pharynx", "Esophagus"], 1),
    ("Which planet has the most moons?", ["Saturn", "Jupiter", "Neptune", "Mars"], 1),
    ("What is the unit of electric resistance?", ["Volt", "Ampere", "Ohm", "Watt"], 2),
    ("Which part of the eye controls light entry?", ["Retina", "Iris", "Lens", "Cornea"], 1),
    ("What is the boiling point of water in Fahrenheit?", ["100", "200", "212", "300"], 2),
    ("Which element is essential for bones?", ["Iron", "Sodium", "Calcium", "Zinc"], 2),
    ("What is the name of the nearest galaxy?", ["Milky Way", "Andromeda", "Triangulum", "Centaurus"], 1),
    ("Which blood type is the universal donor?", ["A+", "B-", "O-", "AB+"], 2),
    ("What is the chemical symbol for Sodium?", ["So", "Sd", "Na", "Ni"], 2),
    ("Which gas is produced by lightning?", ["Ozone", "Oxygen", "Methane", "Nitrogen"], 0),
    ("What is the largest cell in the human body?", ["Sperm", "Neuron", "Egg cell", "Skin cell"], 2),
    ("Which planet is farthest from the Sun?", ["Uranus", "Neptune", "Saturn", "Pluto"], 1),
    ("What is the process of a liquid turning to gas?", ["Melting", "Freezing", "Evaporation", "Condensation"], 2),
    ("Which vitamin helps with blood clotting?", ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], 3),
    ("What is the name for the study of birds?", ["Zoology", "Ornithology", "Entomology", "Botany"], 1),
    ("Which metal is used in thermometers?", ["Iron", "Lead", "Mercury", "Tin"], 2),
    ("What is the hardest bone in the human body?", ["Skull", "Femur", "Jawbone", "Rib"], 2),
    ("Which gas is used in light bulbs?", ["Oxygen", "Argon", "Carbon", "Helium"], 1),
    ("What is the color of liquid oxygen?", ["Clear", "Pale blue", "Pale green", "Red"], 1),
    ("Which planet has a day longer than its year?", ["Mars", "Venus", "Mercury", "Jupiter"], 1),
    ("What is the pH of pure water?", ["5", "6", "7", "8"], 2),
    ("Which layer of the atmosphere contains the ozone layer?", ["Troposphere", "Stratosphere", "Mesosphere", "Exosphere"], 1),
    ("How many hearts does an octopus have?", ["1", "2", "3", "4"], 2),
    ("What is the lightest element?", ["Helium", "Oxygen", "Hydrogen", "Lithium"], 2),
    ("Which animal is the fastest swimmer?", ["Shark", "Dolphin", "Sailfish", "Whale"], 2),
    ("What is the common name for Sodium Chloride?", ["Sugar", "Salt", "Baking Soda", "Vinegar"], 1),
    ("Which planet rotates on its side?", ["Uranus", "Neptune", "Saturn", "Jupiter"], 0),
    ("What is the main gas in the Sun?", ["Oxygen", "Helium", "Hydrogen", "Carbon"], 2),
    ("Which blood vessels carry blood away from the heart?", ["Veins", "Arteries", "Capillaries", "Nerves"], 1),
    ("How many elements are in the periodic table?", ["108", "118", "128", "98"], 1),
    ("What is the basic unit of heredity?", ["Cell", "Gene", "Atom", "Molecule"], 1),
    ("Which bird can fly backwards?", ["Eagle", "Hummingbird", "Owl", "Parrot"], 1),
    ("What is the largest land animal?", ["Rhino", "African Elephant", "Hippo", "Giraffe"], 1),
    ("Which gas is known as 'laughing gas'?", ["Nitrogen", "Nitrous Oxide", "Carbon Monoxide", "Helium"], 1),
    ("How many planets in our solar system have rings?", ["1", "2", "3", "4"], 3),
    ("What is the freezing point of water in Celsius?", ["-10", "0", "10", "32"], 1),
    ("Which planet is known for the Great Red Spot?", ["Mars", "Jupiter", "Saturn", "Neptune"], 1),
    ("What is the chemical symbol for Silver?", ["Si", "Sl", "Ag", "Au"], 2),
    ("Which part of the brain controls balance?", ["Cerebrum", "Cerebellum", "Brainstem", "Thalamus"], 1),
    ("What is the main source of Vitamin C?", ["Meat", "Bread", "Citrus fruits", "Dairy"], 2),
    ("How many lungs does a human have?", ["1", "2", "3", "4"], 1),
    ("What is the speed of sound?", ["343 m/s", "100 m/s", "500 m/s", "1000 m/s"], 0),
    ("Which planet is often called Earth's twin?", ["Mars", "Venus", "Mercury", "Neptune"], 1),
    ("What is the study of plants called?", ["Biology", "Botany", "Zoology", "Ecology"], 1),
    ("Which substance makes up most of the human body?", ["Blood", "Water", "Fat", "Muscle"], 1),
    ("How many teeth does an adult human have?", ["28", "30", "32", "34"], 2),
    ("What is the largest organ in the human body?", ["Liver", "Lungs", "Skin", "Brain"], 2),
    ("Which animal has the largest eyes?", ["Elephant", "Colossal Squid", "Owl", "Whale"], 1),
    ("What is the chemical symbol for Helium?", ["H", "He", "Hi", "Ha"], 1),
    ("Which force keeps planets in orbit?", ["Friction", "Magnetism", "Gravity", "Electricity"], 2),
]

# --- HISTORY (100 UNIQUE) ---
history_data = [
    ("Who was the first President of the USA?", ["Lincoln", "Washington", "Jefferson", "Adams"], 1),
    ("In which year did WW2 end?", ["1944", "1945", "1946", "1947"], 1),
    ("Who built the Great Wall?", ["Romans", "Greeks", "Chinese", "Egyptians"], 2),
    ("Who discovered America in 1492?", ["Magellan", "Columbus", "Vasco da Gama", "Cook"], 1),
    ("Ancient Olympics started in which country?", ["Italy", "Egypt", "Greece", "China"], 2),
    ("Who was the first man on the moon?", ["Aldrin", "Armstrong", "Gagarin", "Collins"], 1),
    ("Which country gifted the Statue of Liberty?", ["UK", "France", "Germany", "Italy"], 1),
    ("In which city is the Eiffel Tower?", ["London", "Berlin", "Paris", "Rome"], 2),
    ("Who was the 'Iron Lady'?", ["Angela Merkel", "Margaret Thatcher", "Indira Gandhi", "Theresa May"], 1),
    ("The Titanic sank in which ocean?", ["Pacific", "Indian", "Atlantic", "Arctic"], 2),
    ("Who was the first female pilot to fly solo across the Atlantic?", ["Earhart", "Johnson", "Coleman", "Cochran"], 0),
    ("Which pharaoh's tomb was found in 1922?", ["Ramses", "Tutankhamun", "Akhenaten", "Seti"], 1),
    ("In which year did the French Revolution start?", ["1779", "1789", "1799", "1809"], 1),
    ("Who wrote the 'I Have a Dream' speech?", ["Malcom X", "MLK Jr.", "Rosa Parks", "Nelson Mandela"], 1),
    ("Which civilization built the Machu Picchu?", ["Aztec", "Maya", "Inca", "Olmec"], 2),
    ("Who was the first Emperor of Rome?", ["Julius Caesar", "Augustus", "Nero", "Caligula"], 1),
    ("Which war was fought between the North and South USA?", ["WWI", "WWII", "Civil War", "Vietnam War"], 2),
    ("Who invented the light bulb?", ["Tesla", "Edison", "Bell", "Newton"], 1),
    ("The Magna Carta was signed in which country?", ["France", "Spain", "England", "Germany"], 2),
    ("Who was the leader of the Soviet Union during WWII?", ["Lenin", "Stalin", "Trotsky", "Khrushchev"], 1),
    ("Which explorer circumnavigated the globe first?", ["Columbus", "Magellan", "Cook", "Drake"], 1),
    ("In which year did the Berlin Wall fall?", ["1987", "1988", "1989", "1990"], 2),
    ("Who was the Greek god of the sea?", ["Zeus", "Hades", "Poseidon", "Apollo"], 2),
    ("Which city was buried by Mt. Vesuvius?", ["Rome", "Naples", "Pompeii", "Venice"], 2),
    ("Who was the Queen of ancient Egypt?", ["Nefertiti", "Cleopatra", "Hatshepsut", "Isis"], 1),
    ("The Renaissance began in which country?", ["France", "Spain", "Italy", "Greece"], 2),
    ("Who was the primary author of the Declaration of Independence?", ["Washington", "Adams", "Jefferson", "Franklin"], 2),
    ("In which year did WWI start?", ["1912", "1914", "1916", "1918"], 1),
    ("Who was known as the 'Sun King'?", ["Louis XIV", "Henry VIII", "Charles V", "Peter the Great"], 0),
    ("Which battle was Napoleon's final defeat?", ["Waterloo", "Leipzig", "Borodino", "Trafalgar"], 0),
    ("Who founded the Mongol Empire?", ["Kublai Khan", "Genghis Khan", "Tamerlane", "Attila"], 1),
    ("Which country was partitioned into North and South in 1945?", ["Germany", "Vietnam", "Korea", "Yemen"], 2),
    ("Who was the first person to sail around Africa to India?", ["Columbus", "Vasco da Gama", "Magellan", "Dias"], 1),
    ("In which century did the Black Death occur?", ["12th", "13th", "14th", "15th"], 2),
    ("Who was the main leader of the Indian Independence movement?", ["Nehru", "Gandhi", "Patel", "Bose"], 1),
    ("The Aztec Empire was in which modern country?", ["Peru", "Mexico", "Brazil", "Chile"], 1),
    ("Who was the 16th President of the USA?", ["Grant", "Lincoln", "Johnson", "Hayes"], 1),
    ("Which invention ended the Middle Ages?", ["Steam Engine", "Printing Press", "Compass", "Telescope"], 1),
    ("Who was the youngest US President?", ["Kennedy", "Roosevelt", "Clinton", "Obama"], 1),
    ("In which year did the Russian Revolution happen?", ["1905", "1911", "1917", "1923"], 2),
    ("Who was the first woman to win a Nobel Prize?", ["Marie Curie", "Mother Teresa", "Jane Addams", "Pearl Buck"], 0),
    ("Which civilization invented the wheel?", ["Egyptian", "Sumerian", "Greek", "Roman"], 1),
    ("Who was the King of the United Kingdom during WWII?", ["Edward VIII", "George VI", "George V", "Edward VII"], 1),
    ("In which year did Apollo 11 land on the moon?", ["1967", "1968", "1969", "1970"], 2),
    ("Who was the leader of the Free French Forces in WWII?", ["Petain", "De Gaulle", "Mitterrand", "Chirac"], 1),
    ("Which city-state won the Peloponnesian War?", ["Athens", "Sparta", "Corinth", "Thebes"], 1),
    ("Who was the legendary King of Camelot?", ["Arthur", "Richard", "Edward", "William"], 0),
    ("In which year did the Crusades begin?", ["1066", "1096", "1126", "1156"], 1),
    ("Who was the primary leader of the Reformation?", ["Calvin", "Luther", "Henry VIII", "Zwingli"], 1),
    ("Which empire was ruled by Suleiman the Magnificent?", ["Persian", "Mughal", "Ottoman", "Byzantine"], 2),
    ("Who wrote 'The Communist Manifesto'?", ["Lenin", "Marx", "Engels", "Mao"], 1),
    ("In which year did the Great Depression start?", ["1927", "1928", "1929", "1930"], 2),
    ("Who was the first woman in space?", ["Tereshkova", "Ride", "Savitskaya", "Resnik"], 0),
    ("Which dynasty built the Forbidden City?", ["Han", "Tang", "Ming", "Qing"], 2),
    ("Who was the main general of the Confederate Army?", ["Grant", "Lee", "Sherman", "Jackson"], 1),
    ("In which year did the Cold War end?", ["1989", "1990", "1991", "1992"], 2),
    ("Who was the god of the Underworld in Greek myth?", ["Zeus", "Hades", "Poseidon", "Hermes"], 1),
    ("Which war was fought over the claim to the French throne?", ["Thirty Years War", "Hundred Years War", "War of the Roses", "Seven Years War"], 1),
    ("Who was the first female Prime Minister of Israel?", ["Golda Meir", "Indira Gandhi", "Benazir Bhutto", "Margaret Thatcher"], 0),
    ("In which year did the American Civil War end?", ["1863", "1864", "1865", "1866"], 2),
    ("Who was the hero of the Battle of Trafalgar?", ["Wellington", "Nelson", "Drake", "Cook"], 1),
    ("Which document contains the first 10 amendments to the US Constitution?", ["Magna Carta", "Bill of Rights", "Declaration of Independence", "Articles of Confederation"], 1),
    ("Who was the last Tsar of Russia?", ["Alexander III", "Nicholas II", "Peter I", "Ivan IV"], 1),
    ("In which year did the Mayflower arrive in America?", ["1610", "1620", "1630", "1640"], 1),
    ("Who was the 'Desert Fox' in WWII?", ["Rommel", "Montgomery", "Patton", "Eisenhower"], 0),
    ("Which civilization developed the first writing system?", ["Egyptian", "Sumerian", "Indus", "Chinese"], 1),
    ("Who was the first Secretary of the Treasury of the USA?", ["Jefferson", "Hamilton", "Madison", "Jay"], 1),
    ("In which year did the Vietnam War end?", ["1973", "1974", "1975", "1976"], 2),
    ("Who was the leader of the Zulu Kingdom?", ["Shaka", "Dingane", "Cetshwayo", "Mpande"], 0),
    ("Which country was the first to give women the vote?", ["USA", "UK", "New Zealand", "Australia"], 2),
    ("Who was the primary leader of the Haitian Revolution?", ["Louverture", "Dessalines", "Christophe", "Petion"], 0),
    ("In which year did the Industrial Revolution begin?", ["1740", "1750", "1760", "1770"], 2),
    ("Who was the first human to orbit the Earth?", ["Gagarin", "Glenn", "Shepard", "Titov"], 0),
    ("Which peace treaty ended WWI?", ["Versailles", "Paris", "Trianon", "Ghent"], 0),
    ("Who was the 'Father of Medicine'?", ["Socrates", "Plato", "Hippocrates", "Aristotle"], 2),
    ("In which year did the Spanish Armada fail?", ["1578", "1588", "1598", "1608"], 1),
    ("Who was the leader of the Khmer Rouge?", ["Ho Chi Minh", "Pol Pot", "Sihanouk", "Lon Nol"], 1),
    ("Which city was the capital of the Byzantine Empire?", ["Rome", "Constantinople", "Athens", "Alexandria"], 1),
    ("Who was the first female Pharaoh of Egypt?", ["Cleopatra", "Nefertiti", "Hatshepsut", "Nefertari"], 2),
    ("In which year was the Magna Carta signed?", ["1205", "1215", "1225", "1235"], 1),
    ("Who was the author of 'The Prince'?", ["Dante", "Machiavelli", "Petrarch", "Boccaccio"], 1),
    ("Which empire was founded by Osman I?", ["Ottoman", "Safavid", "Mughal", "Seljuk"], 0),
    ("Who was the first European to reach India by sea?", ["Columbus", "Vasco da Gama", "Magellan", "Drake"], 1),
    ("In which year did the South Sea Bubble burst?", ["1710", "1720", "1730", "1740"], 1),
    ("Who was the 'Maid of Orleans'?", ["Joan of Arc", "Catherine the Great", "Marie Antoinette", "Victoria"], 0),
    ("Which war was known as 'The Great War'?", ["WWI", "WWII", "Crimean War", "Boer War"], 0),
    ("Who was the first President of South Africa after apartheid?", ["Mandela", "De Klerk", "Mbeki", "Zuma"], 0),
    ("In which year did the Korean War start?", ["1948", "1949", "1950", "1951"], 2),
    ("Who was the architect of the Parthenon?", ["Phidias", "Ictinus", "Callicrates", "Pericles"], 1),
    ("Which explorer named the Pacific Ocean?", ["Columbus", "Vasco da Gama", "Magellan", "Cook"], 2),
    ("Who was the leader of the Mormons to Utah?", ["Joseph Smith", "Brigham Young", "John Taylor", "Wilford Woodruff"], 1),
    ("In which year was the UN founded?", ["1943", "1944", "1945", "1946"], 2),
    ("Who was the first Tudor king?", ["Henry VII", "Henry VIII", "Edward VI", "James I"], 0),
    ("Which battle ended the American Revolution?", ["Saratoga", "Yorktown", "Bunker Hill", "Trenton"], 1),
    ("Who was the primary leader of the Bolsheviks?", ["Lenin", "Stalin", "Trotsky", "Molotov"], 0),
    ("In which year was the Eiffel Tower completed?", ["1887", "1888", "1889", "1890"], 2),
    ("Who was the first female Doctor of Medicine in the USA?", ["Blackwell", "Barton", "Walker", "Lyon"], 0),
    ("Which city was the site of the first atomic bomb use?", ["Tokyo", "Osaka", "Hiroshima", "Nagasaki"], 2),
    ("Who was the 40th President of the USA?", ["Carter", "Reagan", "Bush", "Clinton"], 1),
    ("In which year did the Magna Carta receive royal seal?", ["1215", "1216", "1217", "1218"], 0),
]

# --- MATHS (100 UNIQUE) ---
maths_data = [
    ("What is 12 x 12?", ["124", "144", "164", "184"], 1),
    ("What is the square root of 81?", ["7", "8", "9", "10"], 2),
    ("What is 25% of 100?", ["20", "25", "30", "50"], 1),
    ("How many sides does a triangle have?", ["2", "3", "4", "5"], 1),
    ("What is 10 - 7?", ["2", "3", "4", "5"], 1),
    ("What is 50 + 50?", ["100", "200", "300", "400"], 0),
    ("What is 2 x 2 x 2?", ["4", "6", "8", "10"], 2),
    ("How many minutes are in an hour?", ["50", "60", "70", "80"], 1),
    ("What is 100 / 5?", ["15", "20", "25", "30"], 1),
    ("What is 7 x 8?", ["54", "56", "58", "60"], 1),
    ("How many degrees in a circle?", ["90", "180", "270", "360"], 3),
    ("What is the next number: 2, 4, 6, ...?", ["7", "8", "9", "10"], 1),
    ("What is 1/2 of 10?", ["3", "4", "5", "6"], 2),
    ("How many sides in a square?", ["3", "4", "5", "6"], 1),
    ("What is 1000 - 1?", ["99", "990", "999", "9999"], 2),
    ("What is 9 x 9?", ["72", "81", "90", "99"], 1),
    ("What is 4 squared?", ["8", "12", "16", "20"], 2),
    ("How many meters in a kilometer?", ["10", "100", "1000", "10000"], 2),
    ("What is 3 + 3 x 3?", ["9", "12", "18", "21"], 1),
    ("What is 10% of 200?", ["10", "20", "30", "40"], 1),
    ("How many days in a week?", ["5", "6", "7", "8"], 2),
    ("What is 15 + 15?", ["25", "30", "35", "40"], 1),
    ("What is the Roman numeral for 5?", ["I", "V", "X", "L"], 1),
    ("How many seconds in a minute?", ["30", "40", "50", "60"], 3),
    ("What is 44 / 4?", ["10", "11", "12", "13"], 1),
    ("What is the area of a 2x3 rectangle?", ["5", "6", "7", "8"], 1),
    ("How many grams in a kilogram?", ["100", "500", "1000", "2000"], 2),
    ("What is 13 + 7?", ["18", "19", "20", "21"], 2),
    ("What is 6 x 6?", ["32", "34", "36", "38"], 2),
    ("How many edges on a cube?", ["6", "8", "10", "12"], 3),
    ("What is 100 - 45?", ["45", "55", "65", "75"], 1),
    ("What is 3 cubed (3^3)?", ["9", "18", "27", "36"], 2),
    ("How many years in a decade?", ["5", "10", "20", "50"], 1),
    ("What is 1/4 of 100?", ["20", "25", "30", "40"], 1),
    ("What is 11 x 11?", ["111", "121", "131", "141"], 1),
    ("How many faces on a cube?", ["4", "5", "6", "8"], 2),
    ("What is 80 / 2?", ["30", "40", "50", "60"], 1),
    ("What is 14 + 14?", ["24", "26", "28", "30"], 2),
    ("How many centimeters in a meter?", ["10", "50", "100", "1000"], 2),
    ("What is 5 x 5 x 5?", ["25", "75", "125", "150"], 2),
    ("What is the perimeter of a 3x3 square?", ["9", "12", "15", "18"], 1),
    ("How many hours in a day?", ["12", "24", "36", "48"], 1),
    ("What is 99 + 1?", ["90", "100", "110", "1000"], 1),
    ("What is 20 x 5?", ["80", "90", "100", "110"], 2),
    ("How many sides on an octagon?", ["6", "7", "8", "9"], 2),
    ("What is 1/5 of 50?", ["5", "10", "15", "20"], 1),
    ("What is 16 - 9?", ["5", "6", "7", "8"], 2),
    ("How many months in a year?", ["10", "11", "12", "13"], 2),
    ("What is 3 x 4 x 2?", ["12", "18", "24", "36"], 2),
    ("How many degrees in a right angle?", ["45", "90", "180", "360"], 1),
    ("What is 7 + 7 + 7?", ["14", "21", "28", "35"], 1),
    ("What is 40 / 8?", ["4", "5", "6", "7"], 1),
    ("What is the next prime number after 7?", ["8", "9", "10", "11"], 3),
    ("How many years in a century?", ["10", "50", "100", "1000"], 2),
    ("What is 1/3 of 9?", ["1", "2", "3", "4"], 2),
    ("What is 12 + 13?", ["23", "24", "25", "26"], 2),
    ("How many sides on a pentagon?", ["4", "5", "6", "7"], 1),
    ("What is 8 x 4?", ["24", "28", "32", "36"], 2),
    ("What is 100 - 75?", ["15", "25", "35", "45"], 1),
    ("How many weeks in a year?", ["48", "50", "52", "54"], 2),
    ("What is 2 + 2 x 0?", ["0", "2", "4", "8"], 1),
    ("What is 10 squared?", ["20", "50", "100", "200"], 2),
    ("How many vertices on a triangle?", ["2", "3", "4", "5"], 1),
    ("What is 60 / 12?", ["4", "5", "6", "7"], 1),
    ("What is 19 + 6?", ["23", "24", "25", "26"], 2),
    ("How many ml in a liter?", ["100", "500", "1000", "2000"], 2),
    ("What is 9 x 4?", ["32", "34", "36", "38"], 2),
    ("What is the sum of angles in a triangle?", ["90", "180", "270", "360"], 1),
    ("What is 1/10 of 1000?", ["10", "100", "500", "900"], 1),
    ("How many sides on a decagon?", ["8", "9", "10", "12"], 2),
    ("What is 15 - 8?", ["5", "6", "7", "8"], 2),
    ("What is 5 x 12?", ["50", "55", "60", "65"], 2),
    ("How many days in a leap year?", ["364", "365", "366", "367"], 2),
    ("What is 18 + 18?", ["34", "36", "38", "40"], 1),
    ("What is 200 / 4?", ["40", "50", "60", "70"], 1),
    ("How many inches in a foot?", ["10", "12", "14", "16"], 1),
    ("What is 3 x 3 x 3 x 3?", ["27", "54", "81", "108"], 2),
    ("What is the value of 5!", ["60", "100", "120", "150"], 2),
    ("How many sides on a heptagon?", ["5", "6", "7", "8"], 2),
    ("What is 1/2 + 1/2?", ["1/4", "1/2", "1", "2"], 2),
    ("What is 14 x 2?", ["24", "26", "28", "30"], 2),
    ("What is the average of 10 and 20?", ["12", "15", "18", "25"], 1),
    ("How many millimeters in a centimeter?", ["1", "10", "100", "1000"], 1),
    ("What is 7 x 7?", ["47", "48", "49", "50"], 2),
    ("What is 1000 / 8?", ["100", "125", "150", "200"], 1),
    ("How many years in a millennium?", ["100", "500", "1000", "10000"], 2),
    ("What is 25 x 4?", ["75", "100", "125", "150"], 1),
    ("What is 13 + 13 + 13?", ["36", "39", "42", "45"], 1),
    ("How many sides on a nonagon?", ["7", "8", "9", "10"], 2),
    ("What is 100 - 33?", ["65", "66", "67", "68"], 2),
    ("What is 2 to the power of 5?", ["16", "24", "32", "64"], 2),
    ("How many edges on a tetrahedron?", ["4", "5", "6", "8"], 2),
    ("What is 1/8 of 64?", ["6", "7", "8", "9"], 2),
    ("What is 22 + 22?", ["42", "44", "46", "48"], 1),
    ("How many degrees in a straight line?", ["90", "180", "270", "360"], 1),
    ("What is 9 x 7?", ["56", "63", "70", "77"], 1),
    ("What is the square of 13?", ["149", "159", "169", "179"], 2),
    ("How many faces on a square pyramid?", ["3", "4", "5", "6"], 2),
    ("What is 1000 - 250?", ["650", "750", "850", "950"], 1),
    ("What is 11 + 22 + 33?", ["55", "66", "77", "88"], 1),
]

# --- CODING (100 UNIQUE) ---
coding_data = [
    ("What does HTML stand for?", ["Hyper Text Markup Language", "High Tech Multi Language", "Hyper Tool Meta Logic", "None"], 0),
    ("Which tag is used for a paragraph in HTML?", ["<p>", "<div>", "<span>", "<br>"], 0),
    ("In Python, how do you print 'Hello'?", ["echo 'Hello'", "print('Hello')", "console.log('Hello')", "printf('Hello')"], 1),
    ("Which company made the Java language?", ["Microsoft", "Oracle (Sun)", "Apple", "Google"], 1),
    ("What is a 'string' in coding?", ["A piece of thread", "Sequence of characters", "A number", "A loop"], 1),
    ("Which symbol is used for ID in CSS?", [".", "#", "*", "&"], 1),
    ("What is an 'array'?", ["A function", "A single variable", "A collection of items", "A loop"], 2),
    ("What is 'JS' short for?", ["JavaSystem", "JustScript", "JavaScript", "JointScript"], 2),
    ("Which tag is used for an image?", ["<img>", "<pic>", "<image>", "<src>"], 0),
    ("How do you start a for loop in Python?", ["for i = 1 to 10", "for i in range(10):", "loop i to 10", "while i < 10"], 1),
    ("What does CSS stand for?", ["Creative Style Sheets", "Cascading Style Sheets", "Computer Style Sheets", "Colorful Style Sheets"], 1),
    ("Which language is used for web behavior?", ["HTML", "CSS", "JavaScript", "SQL"], 2),
    ("What is a 'bug' in coding?", ["An insect", "An error", "A feature", "A tool"], 1),
    ("Which tag is used for a list item?", ["<ul>", "<li>", "<ol>", "<list>"], 1),
    ("What does SQL stand for?", ["Strong Query Language", "Structured Query Language", "Simple Query Language", "Speed Query Language"], 1),
    ("In JS, which keyword declares a constant?", ["var", "let", "const", "def"], 2),
    ("Which symbol is used for multiplication in code?", ["x", "*", "&", "."], 1),
    ("What is a 'boolean'?", ["A number", "A string", "A true/false value", "A decimal"], 2),
    ("Which tag creates a heading?", ["<h>", "<head>", "<h1>", "<title>"], 2),
    ("What is 'CMS' short for?", ["Content Management System", "Code Management System", "Control Main System", "Content Main Source"], 0),
    ("Which language is primarily for data science?", ["PHP", "Python", "C++", "Swift"], 1),
    ("What does 'API' stand for?", ["App Page Interface", "Application Programming Interface", "Advanced Program Info", "App Program Init"], 1),
    ("Which bracket is used for arrays in JS?", ["()", "{}", "[]", "<>"], 2),
    ("What is 'IDE'?", ["Integrated Dev Environment", "Internal Data Entry", "Init Dev Engine", "Interface Data Entry"], 0),
    ("Which symbol is used for comments in JS?", ["#", "//", "--", "/*"], 1),
    ("What is 'HTTP'?", ["HyperText Transfer Protocol", "High Text Tool Path", "Hyper Tool Transfer Page", "High Transfer Tech Path"], 0),
    ("Which tag is used for a line break?", ["<lb>", "<br>", "<hr>", "<break>"], 1),
    ("What is 'OOP'?", ["Object Oriented Programming", "Only One Program", "Object Only Path", "Other One Program"], 0),
    ("Which keyword starts a function in Python?", ["func", "function", "def", "init"], 2),
    ("What is a 'loop'?", ["A circle", "Repeating code", "An error", "A variable"], 1),
    ("Which tag is used for a link?", ["<link>", "<a>", "<url>", "<href>"], 1),
    ("What does 'URL' stand for?", ["Uniform Resource Locator", "Unit Resource List", "Universal Real Link", "User Resource Link"], 0),
    ("Which symbol is used for 'not equal'?", ["!=", "==", "==", "><"], 0),
    ("What is 'JSON'?", ["JavaScript Object Notation", "Java System Object Now", "JavaScript Online Now", "Java Scripting Object"], 0),
    ("Which tag defines a table?", ["<table>", "<td>", "<tr>", "<th>"], 0),
    ("What is 'UI'?", ["User Interface", "User Info", "Unit Interface", "Unique Info"], 0),
    ("Which operator is for 'and' in JS?", ["&", "&&", "AND", "|"], 1),
    ("What is 'UX'?", ["User Experience", "User Extra", "Unit Experience", "Unique Extra"], 0),
    ("Which tag is for the document body?", ["<head>", "<body>", "<html>", "<main>"], 1),
    ("What is 'git'?", ["A game", "Version control system", "A language", "A browser"], 1),
    ("Which symbol is for 'strictly equal' in JS?", ["=", "==", "===", "!=="], 2),
    ("What is a 'variable'?", ["A container for data", "A type of code", "An error", "A constant"], 0),
    ("Which tag is for a button?", ["<btn>", "<input>", "<button>", "<click>"], 2),
    ("What is 'frontend'?", ["Server side", "Client side", "Database side", "Code side"], 1),
    ("Which language is used for styling apps?", ["XML", "CSS", "JSON", "Markdown"], 1),
    ("What is 'backend'?", ["Server side", "Client side", "Visual side", "Design side"], 0),
    ("Which tag is for a bold text?", ["<b>", "<bold>", "<strong>", "Both b and strong"], 3),
    ("What is 'compiling'?", ["Running code", "Translating code to machine code", "Writing code", "Deleting code"], 1),
    ("Which symbol is for modulo (remainder)?", ["/", "\\", "%", "*"], 2),
    ("What is 'debugging'?", ["Adding bugs", "Finding and fixing errors", "Writing code", "Testing UI"], 1),
    ("Which tag is used for a division/container?", ["<section>", "<div>", "<part>", "<box>"], 1),
    ("What is 'SSL'?", ["Secure Sockets Layer", "Secure System Logic", "Server Side Logic", "System Side Layer"], 0),
    ("Which language is used for iOS apps?", ["Java", "Swift", "C#", "Kotlin"], 1),
    ("What is 'MVC'?", ["Model View Controller", "Main View Code", "Model Variable Code", "Main Variable Controller"], 0),
    ("Which symbol is for 'or' in JS?", ["&", "||", "OR", "!"], 1),
    ("What is 'SEO'?", ["Search Engine Optimization", "Site Engine Option", "Search Extra Order", "Site Extra Order"], 0),
    ("Which tag is for a script?", ["<js>", "<script>", "<code>", "<action>"], 1),
    ("What is 'AJAX'?", ["Asynchronous JS and XML", "Async Java and XML", "Action JS and XML", "Asynchronous Java Action"], 0),
    ("Which keyword defines a class in JS?", ["object", "class", "def", "struct"], 1),
    ("What is 'RAM'?", ["Random Access Memory", "Read Access Main", "Read All Memory", "Random All Memory"], 0),
    ("Which tag is for a stylesheet link?", ["<style>", "<link>", "<css>", "<head>"], 1),
    ("What is 'responsive design'?", ["Design for fast loading", "Design for all screens", "Design for colors", "Design for fonts"], 1),
    ("Which symbol is used for 'greater than'?", [">", "<", "!", "="], 0),
    ("What is 'npm'?", ["Node Package Manager", "Net Package Manager", "Node Program Main", "None of these"], 0),
    ("Which tag is for an unordered list?", ["<ol>", "<ul>", "<li>", "<list>"], 1),
    ("What is 'DOM'?", ["Document Object Model", "Data Object Model", "Document Online Main", "Data Online Main"], 0),
    ("Which property changes text color in CSS?", ["font-color", "text-color", "color", "background-color"], 2),
    ("What is 'SASS'?", ["A CSS preprocessor", "A JS framework", "A database", "A server"], 0),
    ("Which tag is for a form?", ["<input>", "<form>", "<submit>", "<select>"], 1),
    ("What is 'framework'?", ["A type of loop", "Pre-written code structure", "An error", "A browser"], 1),
    ("Which property sets font size in CSS?", ["text-size", "font-size", "size", "font-style"], 1),
    ("What is 'SQL injection'?", ["A security threat", "A type of code", "A database tool", "An error"], 0),
    ("Which tag is for a table row?", ["<td>", "<tr>", "<th>", "<table>"], 1),
    ("What is 'API endpoint'?", ["A URL", "A variable", "A loop", "An error"], 0),
    ("Which property adds space inside an element?", ["margin", "padding", "border", "spacing"], 1),
    ("What is 'GitHub'?", ["A language", "A host for git repositories", "A browser", "A search engine"], 1),
    ("Which tag is for a text input?", ["<text>", "<input type='text'>", "<textarea>", "<string>"], 1),
    ("What is 'open source'?", ["Private code", "Code free to use/modify", "Paid code", "Secret code"], 1),
    ("Which property adds space outside an element?", ["padding", "margin", "border", "spacing"], 1),
    ("What is 'Markdown'?", ["A database", "A lightweight markup language", "A JS framework", "A styling tool"], 1),
    ("Which tag is for a drop-down list?", ["<list>", "<dropdown>", "<select>", "<input>"], 2),
    ("What is 'CLI'?", ["Command Line Interface", "Code Line Interface", "Command List Info", "Code List Info"], 0),
    ("Which CSS property makes text bold?", ["font-bold", "text-bold", "font-weight", "weight"], 2),
    ("What is 'V8'?", ["An engine for JS", "A car", "A CSS tool", "A database"], 0),
    ("Which tag is for the largest heading?", ["<h6>", "<h0>", "<h1>", "<big>"], 2),
    ("What is 'minification'?", ["Making code smaller", "Making code bigger", "Deleting code", "Hiding code"], 0),
    ("Which property sets the background color?", ["bg-color", "background-color", "color", "fill"], 1),
    ("What is 'NaN'?", ["Not a Number", "Now and Next", "No and Never", "Number and Name"], 0),
    ("Which tag is for an ordered list?", ["<ul>", "<ol>", "<li>", "<list>"], 1),
    ("What is 'Full Stack'?", ["Only frontend", "Only backend", "Both front and backend", "Neither"], 2),
    ("Which property sets the width of an element?", ["size", "width", "breadth", "box-size"], 1),
    ("What is 'cache'?", ["Money", "Temporary storage", "A bug", "A permanent file"], 1),
    ("Which tag is for a footer?", ["<end>", "<bottom>", "<footer>", "<base>"], 2),
    ("What is 'CDN'?", ["Content Delivery Network", "Code Delivery Now", "Content Data Network", "Code Data Network"], 0),
    ("Which property changes the font family?", ["text-font", "font-family", "font-style", "family"], 1),
    ("What is '404'?", ["Success code", "Page not found error", "Redirect code", "Server error"], 1),
    ("Which tag is for a navigation bar?", ["<navbar>", "<nav>", "<menu>", "<header>"], 1),
    ("What is 'localhost'?", ["Your own computer", "The internet", "A remote server", "A database"], 0),
    ("Which symbol is used for 'this' in Python?", ["this", "self", "me", "it"], 1),
    ("What is 'W3C'?", ["Web standards body", "A game", "A browser", "A language"], 0),
]

data_dir = "resources/data"
os.makedirs(data_dir, exist_ok=True)

with open(f"{data_dir}/science.json", "w") as f: json.dump(create_quiz("Science", "Science Mastery", science_data), f, indent=2)
with open(f"{data_dir}/history.json", "w") as f: json.dump(create_quiz("History", "World History", history_data), f, indent=2)
with open(f"{data_dir}/coding.json", "w") as f: json.dump(create_quiz("Coding", "Coding Basics", coding_data), f, indent=2)
with open(f"{data_dir}/maths.json", "w") as f: json.dump(create_quiz("Maths", "Mathematics", maths_data), f, indent=2)

print("Generated 400 100% unique questions.")
