package com.quizcraft.server;

import com.quizcraft.models.Question;
import com.quizcraft.models.Quiz;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class QuizDataGenerator {

    private static final String DATA_DIR = "resources/data";

    public static void generateInitialData() {
        File dir = new File(DATA_DIR);
        if (!dir.exists()) dir.mkdirs();

        try {
            saveQuiz(generateScienceQuiz());
            saveQuiz(generateHistoryQuiz());
            saveQuiz(generateCodingQuiz());
            saveQuiz(generateMathsQuiz());
            System.out.println("✅  Generated initial Java-based quiz data.");
        } catch (IOException e) {
            System.err.println("❌  Error generating quiz data: " + e.getMessage());
        }
    }

    private static void saveQuiz(Quiz quiz) throws IOException {
        String filename = quiz.getCategory().toLowerCase() + ".json";
        Files.write(Paths.get(DATA_DIR, filename), quiz.toJson().getBytes());
    }

    private static Quiz generateScienceQuiz() {
        List<Question> questions = new ArrayList<>();
        questions.add(new Question("What is the powerhouse of the cell?", Arrays.asList("Mitochondria", "Nucleus", "Ribosome", "Cell Wall"), 0));
        questions.add(new Question("Which planet is known as the Red Planet?", Arrays.asList("Venus", "Mars", "Jupiter", "Saturn"), 1));
        questions.add(new Question("What is the chemical symbol for water?", Arrays.asList("WA", "H2O", "HO2", "OH"), 1));
        questions.add(new Question("What gas do plants absorb during photosynthesis?", Arrays.asList("Oxygen", "Nitrogen", "Carbon Dioxide", "Helium"), 2));
        questions.add(new Question("What is the hardest natural substance on Earth?", Arrays.asList("Gold", "Iron", "Diamond", "Quartz"), 2));
        // ... more can be added here
        return new Quiz("science-quiz-java", "Science Mastery", "Science", "Fundamental science questions generated by Java.", questions);
    }

    private static Quiz generateHistoryQuiz() {
        List<Question> questions = new ArrayList<>();
        questions.add(new Question("Who was the first President of the USA?", Arrays.asList("Lincoln", "Washington", "Jefferson", "Adams"), 1));
        questions.add(new Question("In which year did WW2 end?", Arrays.asList("1944", "1945", "1946", "1947"), 1));
        questions.add(new Question("Who discovered America in 1492?", Arrays.asList("Magellan", "Columbus", "Vasco da Gama", "Cook"), 1));
        return new Quiz("history-quiz-java", "World History", "History", "Historical milestones and figures.", questions);
    }

    private static Quiz generateCodingQuiz() {
        List<Question> questions = new ArrayList<>();
        questions.add(new Question("What does HTML stand for?", Arrays.asList("Hyper Text Markup Language", "High Tech Multi Language", "Hyper Tool Meta Logic", "None"), 0));
        questions.add(new Question("In Python, how do you print 'Hello'?", Arrays.asList("echo 'Hello'", "print('Hello')", "console.log('Hello')", "printf('Hello')"), 1));
        questions.add(new Question("Which company made the Java language?", Arrays.asList("Microsoft", "Oracle (Sun)", "Apple", "Google"), 1));
        return new Quiz("coding-quiz-java", "Coding Basics", "Coding", "Introduction to web and software development.", questions);
    }

    private static Quiz generateMathsQuiz() {
        List<Question> questions = new ArrayList<>();
        questions.add(new Question("What is 12 x 12?", Arrays.asList("124", "144", "164", "184"), 1));
        questions.add(new Question("What is the square root of 81?", Arrays.asList("7", "8", "9", "10"), 2));
        questions.add(new Question("How many sides does a triangle have?", Arrays.asList("2", "3", "4", "5"), 1));
        return new Quiz("maths-quiz-java", "Mathematics", "Maths", "Basic arithmetic and geometry.", questions);
    }
}
